targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options for json_serializable
          explicit_to_json: true
          include_if_null: false
          field_rename: snake
          create_to_json: true
      
      retrofit_generator:
        options:
          # Options for retrofit
          generate_http_override: true
          generate_provider: true
      
      riverpod_generator:
        options:
          # Options for riverpod
          provider_name_suffix: Provider
          provider_parameters: true
          generate_provider_parameters: true
      
      build_web_compilers:
        options:
          compiler: dart2js
          dart2js_args:
            - --fast-startup
            - --minify
            - --trust-primitives
            - --trust-type-annotations 