# Generated by Django 4.2.7 on 2025-08-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, help_text='Cover letter', null=True),
        ),
    ]
