# Generated by Django 4.2.7 on 2025-08-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Company description')),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='company_logos/')),
                ('industry', models.CharField(blank=True, help_text='Company industry', max_length=100)),
                ('size', models.CharField(blank=True, choices=[('startup', 'Startup'), ('small', 'Small (1-50 employees)'), ('medium', 'Medium (51-200 employees)'), ('large', 'Large (200+ employees)')], help_text='Company size', max_length=50)),
                ('founded_year', models.IntegerField(blank=True, help_text='Year company was founded', null=True)),
                ('location', models.CharField(blank=True, help_text='Company location', max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the company is verified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=255)),
                ('description', models.TextField(help_text='Job description')),
                ('requirements', models.TextField(blank=True, help_text='Job requirements')),
                ('responsibilities', models.TextField(blank=True, help_text='Job responsibilities')),
                ('employer_id', models.BigIntegerField(help_text='User ID of the employer (from user-service)')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', help_text='Type of job', max_length=50)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive Level')], default='entry', help_text='Experience level required', max_length=50)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum salary', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum salary', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='Salary currency', max_length=3)),
                ('location', models.CharField(blank=True, help_text='Job location', max_length=255)),
                ('is_remote', models.BooleanField(default=False, help_text='Whether the job is remote')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job posting is active')),
                ('application_deadline', models.DateField(blank=True, help_text='Application deadline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Category description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category', null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
            ],
            options={
                'verbose_name': 'Job Category',
                'verbose_name_plural': 'Job Categories',
                'db_table': 'job_categories',
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Skill name', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Skill',
                'verbose_name_plural': 'Job Skills',
                'db_table': 'job_skills',
            },
        ),
        migrations.CreateModel(
            name='UserProfileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('full_name', models.CharField(blank=True, max_length=300)),
                ('user_type', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_profile_cache',
                'indexes': [models.Index(fields=['user_type', 'is_active'], name='user_profil_user_ty_46d2a9_idx'), models.Index(fields=['last_synced'], name='user_profil_last_sy_943005_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobSkillJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this skill is required')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobskill')),
            ],
            options={
                'db_table': 'job_skills_jobs',
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='JobCategoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobcategory')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'db_table': 'job_categories_jobs',
                'unique_together': {('job', 'category')},
            },
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.ManyToManyField(help_text='Job categories', related_name='jobs', through='jobs.JobCategoryJob', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(help_text='Company posting the job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(help_text='Job skills', related_name='jobs', through='jobs.JobSkillJob', to='jobs.jobskill'),
        ),
    ]
