# Generated by Django 4.2.7 on 2025-08-28 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(blank=True, help_text='Primary industry sector (e.g., Technology, Healthcare)', max_length=100)),
                ('size', models.CharField(blank=True, choices=[('startup', 'Startup'), ('small', 'Small (1-50 employees)'), ('medium', 'Medium (51-200 employees)'), ('large', 'Large (200+ employees)')], help_text='Company size classification', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Company location (city, state, country)', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Company website URL for additional information')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if company has been verified by platform')),
                ('employer_id', models.IntegerField(default=1, help_text='ID of the user account associated with this company')),
                ('name', models.CharField(help_text="Skill name (e.g., 'Python', 'Project Management')", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the skill and its applications')),
                ('category', models.CharField(blank=True, help_text="Skill category (e.g., 'Programming', 'Soft Skills')", max_length=50)),
                ('skill_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], help_text='Default proficiency level for this skill', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for UI display', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this skill is active and available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for nested hierarchies (null for top-level)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='jobs.company')),
            ],
            options={
                'verbose_name': 'Job Skill',
                'verbose_name_plural': 'Job Skills',
                'db_table': 'job_skills',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Job title (e.g., 'Senior Software Engineer')", max_length=200)),
                ('description', models.TextField(help_text='Detailed job description, responsibilities, and requirements')),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements and qualifications for the position')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities and duties for the role')),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', help_text='Type of employment arrangement', max_length=50)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead'), ('executive', 'Executive')], default='mid', help_text='Required experience level for the position', max_length=20)),
                ('location', models.CharField(help_text='Job location (city, state, country)', max_length=200)),
                ('is_remote', models.BooleanField(default=False, help_text='Whether the job allows remote work')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum annual salary (USD)', max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum annual salary (USD)', max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='USD', help_text='Salary currency code (e.g., USD, EUR, GBP)', max_length=3)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the job is visible to job seekers')),
                ('employer_id', models.IntegerField(default=1, help_text='ID of the user who posted this job')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(help_text='Company posting this job', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location'], name='jobs_locatio_8650dd_idx'), models.Index(fields=['job_type'], name='jobs_job_typ_e7f4d4_idx'), models.Index(fields=['experience_level'], name='jobs_experie_96c339_idx')],
            },
        ),
    ]
