# Generated by Django 4.2.7 on 2025-08-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employer_id',
            field=models.BigIntegerField(default=1, help_text='ID of the user who posted this job'),
        ),
    ]
