# Generated by Django 4.2.7 on 2025-08-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employer_id',
            field=models.IntegerField(
                default=1,
                help_text='ID of the user account associated with this company'
            ),
        ),
    ]
